version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      SECRET_KEY: "your-secret-key-here-change-in-production"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      DATABASE_URL: "sqlite:///:memory:"
      UPLOAD_DIR: "/app/uploads"
    restart: unless-stopped 